"use client";

import { useMemo, useRef, useState } from "react";
import { upload } from "@vercel/blob/client";
import { AlertTriangle, BarChart3, Check, ChevronRight, Download, FileAudio, FileUp, Headphones, LoaderCircle, Plus, Settings2, ShieldCheck, Trash2, UploadCloud, X } from "lucide-react";

type Criterion = { id: string; name: string; weight: number; description: string };
type AuditSection = { name: string; score: number; weight: number; finding: string; evidence: string };
type AuditResult = { fileName: string; overallScore: number; language: string; summary: string; disposition: "Pass" | "Needs coaching" | "Critical"; sections: AuditSection[]; criticalFailures: string[]; strengths: string[]; coaching: string[]; transcriptExcerpt: string; provider?: string };
type FailedAudit = { fileName: string; reason: string };
const MAX_FILES = 50;
const MAX_FILE_BYTES = 25 * 1024 * 1024;

const DEFAULT_CRITERIA: Criterion[] = [
  { id: "greeting", name: "Opening & professional greeting", weight: 10, description: "Credit any professional greeting, welcome, company/self-introduction or offer to help. Accept English, Hindi, Urdu, Hinglish and semantic equivalents. If the recording starts mid-call, mark the opening not assessable rather than failed." },
  { id: "verification", name: "Customer verification & privacy", weight: 15, description: "For account-specific service, PAN, registered email, DOB, client code/account ID or registered mobile counts as valid basic verification. Do not require verification for general information with no account disclosure. Redact actual identifiers in evidence." },
  { id: "discovery", name: "Listening & problem identification", weight: 15, description: "Allows the customer to explain, identifies the actual broking query, probes relevant facts, confirms understanding and avoids unnecessary interruption." },
  { id: "accuracy", name: "Broking accuracy & process knowledge", weight: 20, description: "Gives accurate guidance for orders, trades, funds/ledger, brokerage/charges, contract notes, holdings, demat/DP, margin/pledge, KYC, login issues, complaints or escalation. Do not invent unsupported process requirements." },
  { id: "resolution", name: "Resolution, ownership & TAT", weight: 15, description: "Provides a correct resolution or appropriate escalation, reference/ticket where applicable, realistic turnaround time, callback commitment and clear next steps." },
  { id: "communication", name: "Communication & empathy", weight: 10, description: "Professional, respectful, understandable and appropriately empathetic communication. Mixed-language service is acceptable when it helps the customer." },
  { id: "compliance", name: "Regulatory compliance & risk", weight: 10, description: "No guaranteed returns, unauthorized advice/trading, mis-selling, concealed risk or charges, fabricated commitment, unsafe data disclosure, abusive conduct or other material compliance breach." },
  { id: "closing", name: "Closing & confirmation", weight: 5, description: "Confirms resolution or next steps, checks whether further help is needed and closes courteously. Do not over-penalize an abruptly disconnected or clipped recording." },
];

const DEMO_RESULT: AuditResult = { fileName: "sample-support-call.mp3", overallScore: 82, language: "Hindi + English", summary: "The advisor resolved the billing query accurately and maintained a calm tone. Verification was incomplete and the closing missed a clear turnaround-time recap.", disposition: "Needs coaching", sections: [
  { name: "Opening & verification", score: 62, weight: 15, finding: "Greeting was clear; two-point verification was not completed.", evidence: "Agent asked for the registered mobile number but did not confirm date of birth." },
  { name: "Listening & discovery", score: 88, weight: 15, finding: "Good probing and no material interruption.", evidence: "Agent restated the disputed charge and confirmed the transaction date." },
  { name: "Accuracy & resolution", score: 91, weight: 25, finding: "Correct explanation and actionable resolution.", evidence: "Agent raised the dispute and gave the correct reference number." },
  { name: "Empathy & ownership", score: 84, weight: 15, finding: "Acknowledged inconvenience and owned the follow-up.", evidence: "I understand why this unexpected charge is concerning." },
  { name: "Communication quality", score: 86, weight: 10, finding: "Professional bilingual communication with minor filler words.", evidence: "The explanation remained concise and easy to follow." },
  { name: "Compliance & privacy", score: 78, weight: 15, finding: "No disclosure, but verification control was incomplete.", evidence: "No account information was disclosed before the partial verification." },
  { name: "Closing", score: 70, weight: 5, finding: "Reference number shared; turnaround time was not reconfirmed.", evidence: "The final recap omitted the expected three-business-day timeline." },
], criticalFailures: [], strengths: ["Accurate dispute resolution", "Calm and empathetic bilingual communication", "Clear ownership of the follow-up"], coaching: ["Complete every mandatory verification point before discussing the account", "Close with reference number, turnaround time and next action", "Replace filler phrases with a short structured recap"], transcriptExcerpt: "Customer: Mere statement mein ek charge dikh raha hai jo maine authorize nahi kiya. Agent: I understand your concern. Let me check the transaction date and raise a dispute for you…" };

const percentTotal = (criteria: Criterion[]) => criteria.reduce((sum, item) => sum + Number(item.weight || 0), 0);
const escapeCsv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function Home() {
  const [criteria, setCriteria] = useState(DEFAULT_CRITERIA); const [files, setFiles] = useState<File[]>([]); const [results, setResults] = useState<AuditResult[]>([]); const [failures, setFailures] = useState<FailedAudit[]>([]); const [selected, setSelected] = useState(0); const [auditing, setAuditing] = useState(false); const [progress, setProgress] = useState(0); const [error, setError] = useState("");
  const fileInput = useRef<HTMLInputElement>(null); const checklistInput = useRef<HTMLInputElement>(null); const totalWeight = percentTotal(criteria); const active = results[selected];
  const batchAverage = useMemo(() => results.length ? Math.round(results.reduce((sum, item) => sum + item.overallScore, 0) / results.length) : 0, [results]);
  const addFiles = (incoming: FileList | null) => { if (!incoming) return; const candidates = Array.from(incoming); const accepted = candidates.filter(file => file.type.startsWith("audio/") || /\.(mp3|wav|m4a|ogg|aac|flac)$/i.test(file.name)); const tooLarge = accepted.filter(file => file.size > MAX_FILE_BYTES); const rejected = candidates.length - accepted.length; const messages = [tooLarge.length ? `${tooLarge.length} file(s) exceeded the 25 MB limit.` : "", rejected ? `${rejected} unsupported file(s) were skipped.` : ""].filter(Boolean); setError(messages.join(" ")); setFiles(current => [...current, ...accepted.filter(file => file.size <= MAX_FILE_BYTES)].filter((file, index, all) => all.findIndex(item => item.name === file.name && item.size === file.size) === index).slice(0, MAX_FILES)); };
  const updateCriterion = (id: string, field: keyof Criterion, value: string | number) => setCriteria(current => current.map(item => item.id === id ? { ...item, [field]: value } : item));
  const importChecklist = async (file?: File) => { if (!file) return; try { const text = await file.text(); let parsed: Criterion[]; if (file.name.endsWith(".json")) { const value = JSON.parse(text); if (!Array.isArray(value)) throw new Error("JSON must contain an array."); parsed = value.map((item, index) => ({ id: `custom-${index}`, name: String(item.name || item.parameter || "").trim(), weight: Number(item.weight), description: String(item.description || item.guidance || "") })); } else { parsed = text.split(/\r?\n/).filter(Boolean).slice(1).map((line, index) => { const [name, weight, description = ""] = line.split(","); return { id: `custom-${index}`, name: name?.trim(), weight: Number(weight), description: description.trim() }; }); } parsed = parsed.filter(item => item.name && Number.isFinite(item.weight) && item.weight > 0); if (!parsed.length) throw new Error("No valid parameters were found."); setCriteria(parsed); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not read the checklist."); } };
  const runAudit = async () => { if (!files.length) return setError("Add at least one audio file first."); if (totalWeight !== 100) return setError("Audit parameter weights must total 100%."); setAuditing(true); setProgress(0); setError(""); setResults([]); setFailures([]); const completed: AuditResult[] = []; const failed: FailedAudit[] = []; for (let index = 0; index < files.length; index++) { const file = files[index]; setProgress(index + 1); try { const safeName = file.name.replace(/[^a-zA-Z0-9._-]+/g, "-"); const blob = await upload(`call-audits/${crypto.randomUUID()}-${safeName}`, file, { access: "public", handleUploadUrl: "/api/upload", clientPayload: JSON.stringify({ size: file.size, type: file.type }) }); const response = await fetch("/api/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ audioUrl: blob.url, fileName: file.name, fileType: file.type, criteria }) }); const payload = await response.json(); if (!response.ok) throw new Error([payload.error, payload.details].filter(Boolean).join(" ")); completed.push({ ...payload.result, provider: payload.provider }); setResults([...completed]); } catch (cause) { failed.push({ fileName: file.name, reason: cause instanceof Error ? cause.message : "Audit failed." }); setFailures([...failed]); } } if (failed.length) setError(`${completed.length} completed; ${failed.length} failed. Successful audits remain available. Use the detailed reason below to retry only failed calls.`); setAuditing(false); setSelected(0); };
  const saveFile = (content: string, type: string, name: string) => { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };
  const downloadExcelReport = async () => { try { setError(""); const response = await fetch("/api/report", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ audits: results, failures }) }); if (!response.ok) { const payload = await response.json(); throw new Error(payload.error || "Excel report generation failed."); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "call-audit-detailed-report.xlsx"; anchor.click(); URL.revokeObjectURL(url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Excel report generation failed."); } };
  const downloadReport = () => { if (!results.length && !failures.length) return; const rows: unknown[][] = [["File", "Overall score", "Disposition", "Language", "Provider", "Parameter", "Parameter score", "Weight", "Finding", "Evidence", "Summary", "Status/Error"]]; results.forEach(item => item.sections.forEach(section => rows.push([item.fileName, item.overallScore, item.disposition, item.language, item.provider || "", section.name, section.score, section.weight, section.finding, section.evidence, item.summary, "Completed"]))); failures.forEach(item => rows.push([item.fileName, "", "", "", "", "", "", "", "", "", "", item.reason])); saveFile(rows.map(row => row.map(escapeCsv).join(",")).join("\n"), "text/csv;charset=utf-8", "call-audit-detailed-report.csv"); };
  const downloadJsonReport = () => saveFile(JSON.stringify({ generatedAt: new Date().toISOString(), summary: { submitted: files.length, completed: results.length, failed: failures.length, averageScore: batchAverage }, audits: results, failures, scorecard: criteria }, null, 2), "application/json", "call-audit-full-report.json");

  return <main className="min-h-screen bg-[#07111f] text-slate-100">
    <header className="border-b border-white/10 bg-[#091728]/95 px-4 py-4 backdrop-blur md:px-7"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-cyan-400 text-[#07111f]"><Headphones size={21}/></div><div><h1 className="font-display text-xl font-bold tracking-tight">Call Audit Studio</h1><p className="text-xs text-slate-400">Multilingual customer-service QA</p></div></div><div className="hidden items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold text-emerald-300 sm:flex"><ShieldCheck size={14}/> Audio is processed only for this audit</div></div></header>
    <div className="mx-auto grid max-w-[1500px] gap-5 p-4 md:p-7 xl:grid-cols-[350px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-white/10 bg-[#0d1b2d] p-4 shadow-2xl shadow-black/10"><div className="flex items-center justify-between"><div><p className="eyebrow">Scorecard</p><h2 className="mt-1 text-lg font-bold">Audit parameters</h2></div><Settings2 className="text-cyan-300" size={20}/></div><div className={`mt-4 flex items-center justify-between rounded-xl px-3 py-2 text-sm ${totalWeight === 100 ? "bg-emerald-400/10 text-emerald-300" : "bg-amber-400/10 text-amber-300"}`}><span>Total weight</span><strong>{totalWeight}%</strong></div>
        <div className="mt-4 max-h-[540px] space-y-3 overflow-y-auto pr-1">{criteria.map(item => <div key={item.id} className="rounded-xl border border-white/8 bg-white/[0.035] p-3"><div className="flex gap-2"><input aria-label="Parameter name" className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none focus:text-cyan-200" value={item.name} onChange={event => updateCriterion(item.id, "name", event.target.value)}/><div className="flex items-center rounded-lg bg-[#07111f] px-2"><input aria-label={`${item.name} weight`} type="number" min="1" max="100" className="w-10 bg-transparent text-right text-sm font-bold outline-none" value={item.weight} onChange={event => updateCriterion(item.id, "weight", Number(event.target.value))}/><span className="text-xs text-slate-500">%</span></div><button aria-label={`Remove ${item.name}`} onClick={() => setCriteria(current => current.filter(entry => entry.id !== item.id))} className="text-slate-500 hover:text-rose-300"><Trash2 size={16}/></button></div><textarea aria-label={`${item.name} guidance`} className="mt-2 min-h-14 w-full resize-none rounded-lg border border-white/8 bg-[#081522] p-2 text-xs leading-5 text-slate-400 outline-none focus:border-cyan-400/40" value={item.description} onChange={event => updateCriterion(item.id, "description", event.target.value)}/></div>)}</div>
        <button onClick={() => setCriteria(current => [...current, { id: crypto.randomUUID(), name: "New parameter", weight: 5, description: "Describe what the auditor should check." }])} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-cyan-300/30 py-2.5 text-sm font-semibold text-cyan-200 hover:bg-cyan-300/5"><Plus size={16}/> Add parameter</button><input ref={checklistInput} type="file" accept=".json,.csv" className="hidden" onChange={event => importChecklist(event.target.files?.[0])}/><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => checklistInput.current?.click()} className="rounded-xl bg-white/8 py-2.5 text-sm font-semibold hover:bg-white/12"><FileUp className="mr-2 inline" size={15}/>Import</button><button onClick={() => setCriteria(DEFAULT_CRITERIA)} className="rounded-xl bg-white/8 py-2.5 text-sm font-semibold hover:bg-white/12">Reset</button></div>
      </aside>
      <section className="min-w-0 space-y-5">
        {!results.length && <div className="rounded-2xl border border-white/10 bg-[#0d1b2d] p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">New audit</p><h2 className="mt-1 font-display text-2xl font-bold">Upload one call or a complete batch</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Supports MP3, WAV, M4A, AAC, OGG and FLAC. Add up to 50 files, maximum 25 MB each. Language is detected automatically.</p></div><div className="rounded-xl bg-cyan-400/10 px-3 py-2 text-xs font-semibold text-cyan-200">English · Hindi · Urdu · Mixed calls</div></div><input ref={fileInput} type="file" accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.flac" multiple className="hidden" onChange={event => { addFiles(event.target.files); event.currentTarget.value = ""; }}/><button onClick={() => fileInput.current?.click()} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); addFiles(event.dataTransfer.files); }} className="mt-6 flex min-h-52 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-cyan-300/35 bg-gradient-to-b from-cyan-300/[0.06] to-transparent p-8 text-center hover:border-cyan-300/60"><div className="grid size-14 place-items-center rounded-2xl bg-cyan-400 text-[#06101c]"><UploadCloud size={27}/></div><strong className="mt-4 text-lg">Choose or drop audio files</strong><span className="mt-1 text-sm text-slate-400">Bulk selection: up to 50 files · 25 MB each</span></button>
          {files.length > 0 && <div className="mt-5 space-y-2"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">Queue ({files.length})</h3><button className="text-xs text-slate-400 hover:text-white" onClick={() => setFiles([])}>Clear all</button></div>{files.map(file => <div key={`${file.name}-${file.size}`} className="flex items-center gap-3 rounded-xl border border-white/8 bg-[#081522] p-3"><FileAudio className="shrink-0 text-cyan-300" size={20}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.name}</p><p className="text-xs text-slate-500">{(file.size / 1024 / 1024).toFixed(1)} MB</p></div><button aria-label={`Remove ${file.name}`} onClick={() => setFiles(current => current.filter(item => item !== file))}><X className="text-slate-500 hover:text-white" size={17}/></button></div>)}</div>}
          {error && <div className="mt-4 flex gap-2 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200"><AlertTriangle className="shrink-0" size={18}/>{error}</div>}{failures.length > 0 && <div className="mt-3 rounded-xl border border-amber-400/20 bg-amber-400/10 p-3 text-xs text-amber-100">{failures.map(item => <p key={item.fileName}><strong>{item.fileName}:</strong> {item.reason}</p>)}</div>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={auditing || !files.length || totalWeight !== 100} onClick={runAudit} className="flex min-h-12 items-center gap-2 rounded-xl bg-cyan-400 px-5 text-sm font-extrabold text-[#06101c] shadow-lg shadow-cyan-500/10 disabled:cursor-not-allowed disabled:opacity-40">{auditing ? <LoaderCircle className="animate-spin" size={18}/> : <BarChart3 size={18}/>} {auditing ? `Auditing ${progress} of ${files.length}` : `Audit ${files.length || "selected"} call${files.length === 1 ? "" : "s"}`}</button><button onClick={() => { setResults([{...DEMO_RESULT}]); setSelected(0); setError(""); }} className="min-h-12 rounded-xl border border-white/12 px-5 text-sm font-bold hover:bg-white/5">View sample result</button></div></div>}
        {results.length > 0 && <><div className="grid gap-3 sm:grid-cols-3"><Metric label="Batch average" value={`${batchAverage}%`} tone="cyan"/><Metric label="Audited calls" value={String(results.length)} tone="violet"/><Metric label="Need attention" value={String(results.filter(item => item.disposition !== "Pass").length)} tone="amber"/></div><div className="grid gap-5 2xl:grid-cols-[300px_minmax(0,1fr)]"><div className="rounded-2xl border border-white/10 bg-[#0d1b2d] p-3"><div className="px-2 py-2"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">Audit results</h3><button onClick={downloadExcelReport} aria-label="Download Excel report" title="Download report in your Excel format" className="flex items-center gap-1 rounded-lg bg-emerald-400/10 px-2.5 py-1.5 text-xs font-bold text-emerald-300 hover:bg-emerald-400/20"><Download size={15}/> Excel</button></div><div className="mt-2 flex gap-3 text-[11px]"><button onClick={downloadReport} className="text-cyan-300 hover:text-cyan-200">CSV</button><button onClick={downloadJsonReport} className="text-violet-300 hover:text-violet-200">JSON</button></div></div><div className="space-y-2">{results.map((item, index) => <button key={`${item.fileName}-${index}`} onClick={() => setSelected(index)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected === index ? "border-cyan-300/40 bg-cyan-300/8" : "border-transparent bg-white/[0.025] hover:bg-white/5"}`}><ScoreRing score={item.overallScore}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.fileName}</p><p className="mt-1 text-xs text-slate-500">{item.language} · {item.disposition} · {item.provider || "AI"}</p></div><ChevronRight size={16} className="text-slate-600"/></button>)}</div>{failures.length > 0 && <div className="mt-3 rounded-xl bg-rose-400/8 p-3 text-xs text-rose-200"><strong>{failures.length} failed</strong>{failures.map(item => <p className="mt-1 truncate" key={item.fileName}>{item.fileName}</p>)}</div>}<button onClick={() => { setResults([]); setFiles([]); setFailures([]); }} className="mt-3 w-full rounded-xl border border-white/10 py-2.5 text-sm font-semibold hover:bg-white/5">Start another audit</button></div>
          {active && <article className="min-w-0 rounded-2xl border border-white/10 bg-[#0d1b2d] p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Detailed evaluation</p><h2 className="mt-1 break-all font-display text-2xl font-bold">{active.fileName}</h2><p className="mt-2 text-sm text-slate-400">Detected: {active.language}</p></div><div className="flex items-center gap-3"><ScoreRing score={active.overallScore} large/><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${active.disposition === "Pass" ? "bg-emerald-400/10 text-emerald-300" : active.disposition === "Critical" ? "bg-rose-400/10 text-rose-300" : "bg-amber-400/10 text-amber-300"}`}>{active.disposition}</span></div></div><p className="mt-5 rounded-xl bg-white/[0.035] p-4 text-sm leading-6 text-slate-300">{active.summary}</p><div className="mt-6 space-y-3"><h3 className="font-bold">Parameter scores</h3>{active.sections.map(section => <div key={section.name} className="rounded-xl border border-white/8 bg-[#081522] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{section.name}</strong><span className="font-display text-lg font-bold text-cyan-300">{section.score}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-violet-400" style={{ width: `${section.score}%` }}/></div><p className="mt-3 text-sm text-slate-300">{section.finding}</p><p className="mt-2 border-l-2 border-cyan-300/30 pl-3 text-xs italic leading-5 text-slate-500">Evidence: {section.evidence}</p></div>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Insight title="What went well" items={active.strengths} good/><Insight title="Coaching actions" items={active.coaching}/></div>{active.criticalFailures.length > 0 && <div className="mt-4 rounded-xl border border-rose-400/20 bg-rose-400/8 p-4"><h3 className="flex items-center gap-2 font-bold text-rose-300"><AlertTriangle size={18}/> Critical failures</h3><ul className="mt-3 space-y-2 text-sm text-rose-100">{active.criticalFailures.map(item => <li key={item}>• {item}</li>)}</ul></div>}<div className="mt-5 rounded-xl border border-white/8 p-4"><h3 className="font-bold">Transcript evidence</h3><p className="mt-3 text-sm leading-7 text-slate-400">{active.transcriptExcerpt}</p></div></article>}</div></>}
      </section>
    </div>
  </main>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone: "cyan" | "violet" | "amber" }) { const color = tone === "cyan" ? "text-cyan-300" : tone === "violet" ? "text-violet-300" : "text-amber-300"; return <div className="rounded-2xl border border-white/10 bg-[#0d1b2d] p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 font-display text-3xl font-bold ${color}`}>{value}</p></div>; }
function ScoreRing({ score, large = false }: { score: number; large?: boolean }) { return <div className={`grid shrink-0 place-items-center rounded-full border-[3px] ${large ? "size-16 text-lg" : "size-11 text-sm"} ${score >= 85 ? "border-emerald-400 text-emerald-300" : score >= 70 ? "border-amber-400 text-amber-300" : "border-rose-400 text-rose-300"}`}><strong>{score}</strong></div>; }
function Insight({ title, items, good = false }: { title: string; items: string[]; good?: boolean }) { return <div className={`rounded-xl border p-4 ${good ? "border-emerald-400/15 bg-emerald-400/[0.05]" : "border-violet-400/15 bg-violet-400/[0.05]"}`}><h3 className={`flex items-center gap-2 font-bold ${good ? "text-emerald-300" : "text-violet-300"}`}>{good ? <Check size={18}/> : <Headphones size={18}/>} {title}</h3><ul className="mt-3 space-y-2 text-sm leading-5 text-slate-300">{items.map(item => <li key={item} className="flex gap-2"><span className="text-slate-600">•</span>{item}</li>)}</ul></div>; }
